настроил API
DimaSit168/SitnikovTKI411 pull request #5
Opened 2021-12-06 15:04 UTC by DimaSit168

2021-12-10 13:05 UTC, MarinaPaley approved these changes
Делайте реализацию.
В АPI (для усложнения задачи и возможности показать самостоятельность решения) добавьте  метод Find, который возвращает номер в стеке, если нашел, и метод Contains,  который возвращает true, если нашел элемент (false, если не нашел)

2021-12-29 16:01 UTC, DimaSit168 commented
Начал писать int и тесты

2022-01-12 12:44 UTC, MarinaPaley requested changes
Если не будете реализовывать все конструкторы и операторы, описанные в `private` секции, то явно запретите их использование ` = delete`

2022-01-12 12:44 UTC, MarinaPaley commented on Project1/StaticLib1/StaticLib1.h
> +	StaticLib1();
Что за "говорящее" название для структуры??????

2022-01-12 12:44 UTC, MarinaPaley commented on Project1/StaticLib1/StaticLib1.h
> +	StaticLib1(const std::initializer_list<int> value);
Чем эта строка отличается от строки 18?

2022-01-12 12:44 UTC, MarinaPaley commented on Project1/StaticLib1/StaticLib1.h
> +	~StaticLib1();
еще один деструктр?

2022-01-12 12:44 UTC, MarinaPaley commented on Project1/StaticLib1/StaticLib1.h
> +	void Remove();
Что будет делать данная функция? Где документация на нее?

2022-01-17 08:00 UTC, DimaSit168 commented
Внесены изменения

2022-01-17 10:00 UTC, merged